-- YEAR_DEV ==  분화된 연도별 가장 큰 대장균의 크기 - 각 대장균의 크기
-- PARTITION BY로 최대값 구하기

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR
    , MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV 
    , ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV ASC
