-- solution 1 : 서브쿼리 where절에서 메인쿼리 테이블 호출

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO I1
WHERE FAVORITES IN
(
 SELECT MAX(FAVORITES)
 FROM REST_INFO I2
 WHERE I1.FOOD_TYPE = I2.FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC

-- solution 2: food_type까지 서브쿼리 selecr절에 넘겨주기

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN
(
SELECT FOOD_TYPE, MAX(FAVORITES)
FROM REST_INFO
GROUP BY FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC

